### PR TITLE
Unraid Template

### PR DESCRIPTION
**Pull request by jaburges**
Todo:
Donation URL
Template URL (this file location)
Icon file (needs uploading from attachment https://github.com/TradeFace/tuyagateway/issues/89)

### CODE REVIEW

**Comment by TradeFace** [comment]
Does this file has to live at root? Would prefer to have it in ./etc/ if possible. 
And please target the PR to the dev branch.

**Comment by jaburges** [comment]
moved it to dev branch
it can go anywhere I think /Unraid_template/ for example if that helps?
I dont think I can move it now, but if you merge then I can move it (and update with the docker hub location whoop whoop)

**Comment by TradeFace** [comment]
The template as I understand it mostly configuration. So imo /etc would the correct location.  Later on some of the other files should be moved from the root where possible. (to keep the project somewhat clean)

**Comment by jaburges** [comment]
Hi @TradeFace I realize that we'll need to add your repo to the Unraid list, however there is an easier way too.

This group maintains a bunch of templates - so if its cool with you i'll add it here: https://github.com/selfhosters/unRAID-CA-templates

using your template etc.

**Comment by jaburges** [comment]
https://github.com/selfhosters/unRAID-CA-templates/pull/212

**Comment by TradeFace** [comment]
alright, do you  need any action from my side?

**Comment by jaburges** [comment]
> alright, do you need any action from my side?

nope - all good buddy - just FYI (hand some spare time)

**Pull request merged**
